name: flutter_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  google_sign_in:
  intl:
  firebase_messaging: ^6.0.16
  firebase_auth:
  cloud_firestore:
  shared_preferences: ^0.5.8
  fluttertoast:
  image_picker:
  cached_network_image: ^2.2.0+1
  firebase_storage: ^3.1.6
  simple_animations: ^1.3.3
  emoji_picker: ^0.1.0
  photo_view: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/light-1.png
    - images/background.png
    - images/light-2.png
    - images/clock.png
    - images/google.png
    - images/ash.gif
    - images/a1.gif
    - images/a2.gif
    - images/a3.gif
    - images/a4.gif
    - images/capmarvel.gif
    - images/captain.gif
    - images/captain2.gif
    - images/d1.gif
    - images/d2.gif
    - images/d3.gif
    - images/d4.gif
    - images/hand.gif
    - images/hulk.gif
    - images/iron.gif
    - images/logo2.png
    - images/logo3.png
    - images/n1.gif
    - images/n2.gif
    - images/n3.gif
    - images/n4.gif
    - images/panther.gif
    - images/spidi.gif
    - images/spidifun.gif
    - images/thor.gif
    -
    - images/blas.gif
    - images/bone.gif
    - images/bulba.gif
    - images/butterfi.gif
    - images/dog.gif
    - images/evo.gif
    - images/fire.gif
    - images/fly.png
    - images/oak.gif
    - images/pika.gif
    - images/sing.gif
    - images/tokipi.png
    - images/troc.gif
    - images/pokeball.png
    - images/ash.gif


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
